name: swift_chat
description: A highly customizable and easy-to-use chat UI package for Flutter. It provides a complete chat screen designed to be powered by a real-time backend like WebSockets.
version: 1.1.2 # Updated version
homepage: https://github.com/your_username/swift_chat # TODO: Change to your actual repository URL
repository: https://github.com/your_username/swift_chat # Recommended for pub.dev score

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for Dart 3 and newer
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to latest lints

# The following section is specific to Flutter.
flutter:
  # This package does not have any platform-specific assets or fonts.
